##
## Docker Compose provides a quick way to bring required components up and running for local development
##

version: '3.9'

services:

  # DB
  mysql8:
    platform: linux/amd64
    container_name: mysql8-database
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      -  sql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_management_db
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Message broker
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  sql_data: